version: 2
updates:
  # Python backend (requirements.txt)
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(pip)"
    groups:
      pip-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Root-level Python (if you keep a top-level requirements.txt)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(pip-root)"
    groups:
      pip-root-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Frontend npm (if applicable)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(npm)"
    groups:
      npm-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"# To get started with Dependabot version updates, you'll need to specify which
