version: 2
updates:
  # Keep other ecosystems here if you use them (python, github-actions, etc.)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    # group everything, but restrict to patch/minor
    groups:
      frontend-weekly:
        patterns: ["*"]
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
    ignore:
      # Block *all* majors temporarily
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      # Hard block ESLint >=9 specifically (even if minor)
      - dependency-name: "eslint"
        versions: [">=9"]
      # Block @typescript-eslint majors explicitly
      - dependency-name: "@typescript-eslint/*"
        update-types: ["version-update:semver-major"]
      # Block React 19 majors explicitly
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
