# fly.toml for DHK Align backend (FastAPI + SQLite)
app = "dhkalign-backend"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  BACKEND_CACHE_TTL = "180"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = "10s"
    timeout  = "2s"
    grace_period = "30s"
    method   = "GET"
    path     = "/health"

[[mounts]]
  source = "dhkalign_data"
  destination = "/app/backend/data"
