app = "dhkalign-backend"
primary_region = "iad"

[build]
  # Build uses backend/Dockerfile in this directory

[env]
  ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[mounts]
  source = "dhkalign_data"
  destination = "/data"
