name = "dhkalign-edge"
main = "src/index.js"
compatibility_date = "2025-09-06"

[[kv_namespaces]]
binding = "CACHE"
id = "97e93c549954436f8370f6e7894ad6ef"
preview_id = "80b3191e204c4632934491dbb70743b7"

[[kv_namespaces]]
binding = "USAGE"
id = "d1f0c46aba204abc8fce5de642106a2a"
preview_id = "a9d2380aee074c678f7cc52220969bc4"

[vars]
ORIGIN_BASE_URL = "https://backend.dhkalign.com"
CACHE_TTL_SECONDS = "300"
REQUIRE_API_KEY = "false"
DEFAULT_API_KEY = "dev"
ALLOWED_ORIGINS = "https://dhkalign.com,https://www.dhkalign.com,http://127.0.0.1:5173,http://localhost:5173"


# -----------------------------
# Production environment config
# -----------------------------
[env.production.vars]
# TODO: set this to your public backend or tunnel URL before deploy
ORIGIN_BASE_URL = "https://backend.dhkalign.com"
REQUIRE_API_KEY = "true"
CACHE_TTL_SECONDS = "300"
DEFAULT_API_KEY = ""
ALLOWED_ORIGINS = "https://dhkalign.com,https://www.dhkalign.com,http://127.0.0.1:5173,http://localhost:5173"

# Optional: bind a custom route once your zone is on Cloudflare
# [env.production]
# routes = [
#   { pattern = "api.dhkalign.com/*", zone_name = "dhkalign.com" }
# ]

[env.production]
kv_namespaces = [
  { binding = "CACHE", id = "97e93c549954436f8370f6e7894ad6ef" },
  { binding = "USAGE", id = "d1f0c46aba204abc8fce5de642106a2a" }
]
