name: Smoke
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Apex front door
        run: |
          set -euo pipefail
          curl -sI https://dhkalign.com | head -n1 | grep -E ' 200 '

      - name: www redirects to apex
        run: |
          set -euo pipefail
          code=$(curl -s -o /dev/null -w '%{http_code}' "https://www.dhkalign.com/test?q=1")
          [ "$code" = "301" ] || { echo "Expected 301, got $code"; exit 1; }

- name: Edge version (CI-safe, backend fallback)
  run: |
    set -euo pipefail
    UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/124 Safari/537.36"
    curl_edge() {
      curl -sS --retry 2 --retry-all-errors -A "$UA" -H 'accept: application/json' -o edge.json -w '%{http_code}' https://edge.dhkalign.com/version || true
    }
    curl_backend() {
      curl -sS --retry 2 --retry-all-errors -H 'accept: application/json' -o backend.json -w '%{http_code}' https://backend.dhkalign.com/version || true
    }
    CODE=$(curl_edge)
    echo "--- edge /version ($CODE) ---"
    jq . < edge.json || cat edge.json || true
    if [ "$CODE" = "200" ]; then
      jq -e '
        ( .sha? // .commit? // .version? // empty | tostring | test("^[0-9a-fA-F]{7,40}$") )
        or ( .. | scalars | tostring | test("^[0-9a-fA-F]{7,40}$") )
      ' < edge.json
    else
      echo "Edge /version non-200 ($CODE) — falling back to backend /version"
      CODE_B=$(curl_backend)
      echo "--- backend /version ($CODE_B) ---"
      jq . < backend.json || cat backend.json || true
      [ "$CODE_B" = "200" ] || { echo "backend /version non-200: $CODE_B"; exit 1; }
      jq -e '
        ( .sha? // .commit? // .version? // empty | tostring | test("^[0-9a-fA-F]{7,40}$") )
        or ( .. | scalars | tostring | test("^[0-9a-fA-F]{7,40}$") )
      ' < backend.json
    fi
      - name: Backend health (via domain)
        run: |
          set -euo pipefail
          curl -fsS https://backend.dhkalign.com/health | jq -e '(.status?=="ok") or (.ok?==true)'

      - name: Free translate #1
        run: |
          set -euo pipefail
          OUT="$(curl -fsS --get "https://edge.dhkalign.com/api/translate" --data-urlencode "q=Rickshaw pabo na")"
          echo "$OUT" | jq . || true
          echo "$OUT" | jq -e 'has("translation") or has("output") or has("result") or has("data")'

      - name: Free translate #2
        run: |
          set -euo pipefail
          curl -fsS --get "https://edge.dhkalign.com/api/translate" --data-urlencode "q=Rickshaw pabo na" \
          | jq -e 'has("translation") or has("output") or has("result") or has("data")'
