name: Smoke
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '17 * * * *'

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update -y && sudo apt-get install -y jq

      - name: Edge health
        run: curl -fsS --retry 3 --retry-all-errors --max-time 20 \
             https://edge.dhkalign.com/edge/health | jq -e '(.ok==true) or (.status=="ok")'

      - name: Backend health (fly.dev)
        run: curl -fsS --retry 3 --retry-all-errors --max-time 20 \
             https://backend.dhkalign.com/health | jq -e '(.ok==true) or (.status=="ok")'

      - name: Free translate (1)
        run: curl -fsS --retry 3 --retry-all-errors --max-time 20 \
             'https://edge.dhkalign.com/api/translate?q=Rickshaw%20pabo%20na' \
             | jq -e '(.ok==true) or (.translation!=null) or (.result!=null)'

      - name: Free translate (2)
        run: curl -fsS --retry 3 --retry-all-errors --max-time 20 \
             'https://edge.dhkalign.com/api/translate?q=Rickshaw%20pabo%20na' \
             | jq -e '(.ok==true) or (.translation!=null) or (.result!=null)'

      - name: Pro translate (skip on PR)
        if: ${{ github.event_name != 'pull_request' }}
        env:
          PROD_API_KEY: ${{ secrets.PROD_API_KEY }}
        run: |
          MISS="gpt_probe_$(date +%s)"
          curl -fsS --retry 3 --retry-all-errors --max-time 30 -X POST \
            'https://edge.dhkalign.com/translate/pro' \
            -H 'content-type: application/json' -H "x-api-key: $PROD_API_KEY" \
            -d "{\"text\":\"$MISS\",\"src_lang\":\"bn-rom\",\"tgt_lang\":\"en\"}" \
            | jq -e '(.ok==true) or (.translation!=null) or (.result!=null)'
