name: Smoke
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Apex front door
        run: |
          set -euo pipefail
          curl -sI https://dhkalign.com | head -n1 | grep -E ' 200 '

      - name: www redirects to apex
        run: |
          set -euo pipefail
          code=$(curl -s -o /dev/null -w '%{http_code}' "https://www.dhkalign.com/test?q=1")
          [ "$code" = "301" ] || { echo "Expected 301, got $code"; exit 1; }

      - name: Edge health (CI-safe)
        run: |
          set -euo pipefail
          UA="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/124 Safari/537.36"
          code=$(curl -sS -A "$UA" -H 'accept: application/json' -o body.json -w '%{http_code}' \
                 https://edge.dhkalign.com/edge/health || true)
          echo "--- edge body ($code) ---"
          jq . < body.json || cat body.json || true
          [ "$code" = "200" ] || { echo "Edge health non-200: $code"; exit 1; }

      - name: Backend health (via domain)
        run: |
          set -euo pipefail
          curl -fsS https://backend.dhkalign.com/health | jq -e '(.status?=="ok") or (.ok?==true)'

      - name: Free translate (1) via Worker
        run: |
          set -euo pipefail
          OUT="$(curl -fsS --get "https://edge.dhkalign.com/api/translate" --data-urlencode "q=Rickshaw pabo na")"
          echo "$OUT" | jq . || true
          echo "$OUT" | jq -e 'has("translation") or has("output") or has("result") or has("data")'

      - name: Free translate (2) via Worker (cache ok)
        run: |
          set -euo pipefail
          curl -fsS --get "https://edge.dhkalign.com/api/translate" --data-urlencode "q=Rickshaw pabo na" \
          | jq -e 'has("translation") or has("output") or has("result") or has("data")'
