name: Smoke
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '17 * * * *'
jobs:
  smoke:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq
      - name: Edge health
        run: curl -fsS --retry 3 --retry-all-errors --max-time 20 https://dhkalign-edge-production.tnfy4np8pm.workers.dev/edge/health | jq -e '.ok==true or .status=="ok"'
      - name: Backend health
        run: curl -fsS --retry 3 --retry-all-errors --max-time 20 https://backend.dhkalign.com/health | jq -e '.ok==true'
      - name: Free translate twice (expect cache hit second time)
        run: |
          curl -fsS --retry 3 --retry-all-errors --max-time 20 'https://dhkalign-edge-production.tnfy4np8pm.workers.dev/translate?q=Rickshaw%20pabo%20na' | jq -e '.ok==true'
          # Second call: allow either cache_hit==true OR no cache_hit field but ok==true (workers may omit the flag)
          curl -fsS --retry 3 --retry-all-errors --max-time 20 'https://dhkalign-edge-production.tnfy4np8pm.workers.dev/translate?q=Rickshaw%20pabo%20na' | jq -e '(.cache_hit==true) or (.ok==true and has("cache_hit")|not)'
      - name: Pro miss forces GPT and DB backfill
        if: ${{ github.event_name != 'pull_request' }}
        env:
          PROD_API_KEY: ${{ secrets.PROD_API_KEY }}
        run: |
          MISS="gpt_probe_$(date +%s)"
          curl -fsS --retry 3 --retry-all-errors --max-time 30 -X POST 'https://dhkalign-edge-production.tnfy4np8pm.workers.dev/translate/pro' \
            -H 'content-type: application/json' -H "x-api-key: $PROD_API_KEY" \
            -d "{\"text\":\"$MISS\",\"src_lang\":\"bn-rom\",\"tgt_lang\":\"en\"}" | jq -e '.ok==true'
