name: smoke
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Free GET via Edge /api/translate
        run: |
          set -euo pipefail
          URL="https://edge.dhkalign.com/api/translate"
          PHRASE="Rickshaw pabo na"
          OUT="$(curl -fsS -G "$URL" --data-urlencode "q=$PHRASE")"
          echo "$OUT" | jq -e 'has("tgt_text") or has("translation") or has("data")' >/dev/null

      - name: PRO via backend proxy (no secrets in CI)
        run: |
          set -euo pipefail
          RES=$(curl -fsS -X POST https://backend.dhkalign.com/api/pro-translate \
            -H 'content-type: application/json' \
            -d '{"q":"Rickshaw pabo na"}')
          echo "$RES" | jq -e 'type=="object"'
          echo "$RES"

      - name: Pages serves JS, not HTML
        run: |
            set -euo pipefail
            UA="Mozilla/5.0"
            ASSET=$(curl -s -A "$UA" https://dhkalign.com/ | grep -oE '/assets/[^"]+\\.js' | head -n1 || true)
            echo "asset=$ASSET"
            [ -n "$ASSET" ] || (echo "no asset found in HTML" && exit 1)
            CT=$(curl -sSI -A "$UA" "https://dhkalign.com$${ASSET}" | tr -d '\r' | awk 'tolower($1$2)=="content-type:"{print tolower($2)}')
            echo "ct=$CT"
            echo "$CT" | grep -q 'javascript' || (echo "asset served not as JS" && exit 1)
